sudo: required
services:
  - docker

before_install:
  - docker build -t ankushem/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ankushem/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "dockerreact"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-125336879883"
  bucket_path: "dockerreact"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"